//! `lease` — one row per outstanding auth-broker lease.
//!
//! Auth-broker INSERTs a row when an OPAQUE login handshake
//! completes, looks the row up by [`Model::bearer_hash`] on every
//! request to validate-and-extend, UPDATEs [`Model::idle_extends_to`]
//! on each use, and sets [`Model::revoked_at`] on explicit revoke /
//! password change / admin action. See botworkz/botwork#141 and the
//! parent RFE botworkz/botwork-extra#123 for the surrounding design.
//!
//! ## Lifecycle
//!
//! ```text
//!    (login)                              (revoke / expire)
//!    INSERT ──► revoked_at IS NULL ──► UPDATE revoked_at ──► (janitor DELETE)
//!                   │
//!                   └─ UPDATE idle_extends_to on each /auth/check
//! ```
//!
//! The per-tenant `max_lease` policy + the janitor that walks
//! `revoked_at IS NOT NULL OR expires_at < now()` live in auth-broker,
//! not here. This entity is the storage shape only.
//!
//! ## Hash, not bearer
//!
//! [`Model::bearer_hash`] is the SHA-256 of the bearer token; the
//! bearer plaintext is **never** stored. A postgres dump leaks lease
//! metadata, not usable bearers. SHA-256 (rather than a
//! password-hardening KDF) is correct here because the bearer is a
//! high-entropy random value generated by auth-broker — there is no
//! human-chosen secret to slow-hash.
//!
//! Auth-broker hashes the incoming `Authorization: Bearer <token>`
//! and looks up by hash; the [`ux_lease_bearer_hash`] UNIQUE index
//! drives that hot path.
//!
//! [`ux_lease_bearer_hash`]: https://github.com/botworkz/botwork/blob/main/db/migration/src/lib.rs
//!
//! ## `wrapped_export_key`
//!
//! Auth-broker needs the per-tenant vault unlock key (the OPAQUE
//! `export_key`) to release secrets on every request. The
//! `export_key` is known to the server only during the OPAQUE
//! handshake; we stash it here wrapped under a process-side wrapping
//! key so a postgres-only snapshot does not reveal it. Wrapping-key
//! management is auth-broker's concern (a process-local tmpfs seed,
//! a KMS, etc.) — out of scope for this entity.
//!
//! ## `ON DELETE` semantics
//!
//! `tenant_id → tenant.id` **CASCADE** — a lease without a tenant is
//! meaningless. The deliberate-two-step "drop workspaces first"
//! posture still lives at `workspace.tenant_id` RESTRICT.

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "lease")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    /// FK → `tenant.id`. CASCADE on tenant delete.
    pub tenant_id: Uuid,
    /// SHA-256 of the bearer token (32 bytes). UNIQUE; auth-broker
    /// looks the row up by this column on every request.
    #[sea_orm(unique)]
    pub bearer_hash: Vec<u8>,
    /// OPAQUE `export_key` sealed under auth-broker's wrapping key.
    /// Opaque to postgres; auth-broker is the only reader/writer.
    pub wrapped_export_key: Vec<u8>,
    /// First successful login completion. Immutable.
    pub issued_at: ChronoDateTimeUtc,
    /// Hard ceiling; the request can ask for less but never more than
    /// the tenant `max_lease` cap (enforced in auth-broker).
    pub expires_at: ChronoDateTimeUtc,
    /// `min(expires_at, now + idle_window)`. Bumped on each
    /// `/auth/check`; the value never exceeds [`Self::expires_at`].
    pub idle_extends_to: ChronoDateTimeUtc,
    /// `NULL` while the lease is live. Set to a wall-clock timestamp
    /// on explicit revoke / password change / admin action; the row
    /// then sits as terminal audit state until the janitor sweeps it
    /// alongside expired rows.
    pub revoked_at: Option<ChronoDateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// Belongs to a tenant. CASCADE on tenant delete — a lease
    /// without a tenant is meaningless.
    #[sea_orm(
        belongs_to = "super::tenant::Entity",
        from = "Column::TenantId",
        to = "super::tenant::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Tenant,
}

impl Related<super::tenant::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tenant.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
